/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LiveDemoRouteImport } from './routes/live-demo'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComparisonAiVsVirtualReceptionistRouteImport } from './routes/comparison-ai-vs-virtual-receptionist'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemoRoute = LiveDemoRouteImport.update({
  id: '/live-demo',
  path: '/live-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonAiVsVirtualReceptionistRoute =
  ComparisonAiVsVirtualReceptionistRouteImport.update({
    id: '/comparison-ai-vs-virtual-receptionist',
    path: '/comparison-ai-vs-virtual-receptionist',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/comparison-ai-vs-virtual-receptionist': typeof ComparisonAiVsVirtualReceptionistRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/live-demo': typeof LiveDemoRoute
  '/packages': typeof PackagesRoute
  '/presentation': typeof PresentationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/comparison-ai-vs-virtual-receptionist': typeof ComparisonAiVsVirtualReceptionistRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/live-demo': typeof LiveDemoRoute
  '/packages': typeof PackagesRoute
  '/presentation': typeof PresentationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/comparison-ai-vs-virtual-receptionist': typeof ComparisonAiVsVirtualReceptionistRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/live-demo': typeof LiveDemoRoute
  '/packages': typeof PackagesRoute
  '/presentation': typeof PresentationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/comparison-ai-vs-virtual-receptionist'
    | '/contact'
    | '/industries'
    | '/live-demo'
    | '/packages'
    | '/presentation'
    | '/sitemap.xml'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/comparison-ai-vs-virtual-receptionist'
    | '/contact'
    | '/industries'
    | '/live-demo'
    | '/packages'
    | '/presentation'
    | '/sitemap.xml'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/comparison-ai-vs-virtual-receptionist'
    | '/contact'
    | '/industries'
    | '/live-demo'
    | '/packages'
    | '/presentation'
    | '/sitemap.xml'
    | '/solutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComparisonAiVsVirtualReceptionistRoute: typeof ComparisonAiVsVirtualReceptionistRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  LiveDemoRoute: typeof LiveDemoRoute
  PackagesRoute: typeof PackagesRoute
  PresentationRoute: typeof PresentationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demo': {
      id: '/live-demo'
      path: '/live-demo'
      fullPath: '/live-demo'
      preLoaderRoute: typeof LiveDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison-ai-vs-virtual-receptionist': {
      id: '/comparison-ai-vs-virtual-receptionist'
      path: '/comparison-ai-vs-virtual-receptionist'
      fullPath: '/comparison-ai-vs-virtual-receptionist'
      preLoaderRoute: typeof ComparisonAiVsVirtualReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComparisonAiVsVirtualReceptionistRoute:
    ComparisonAiVsVirtualReceptionistRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  LiveDemoRoute: LiveDemoRoute,
  PackagesRoute: PackagesRoute,
  PresentationRoute: PresentationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
